routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//  Clients controller starts from here

use App\Http\Controllers\UserController;

Route::resource('clients', 'ClientsController');


// Departments controller starts from here
Route::resource('departments', 'DepartmentsController');

//  Clients controller starts from here


//  Todo controller starts from here

Route::GET('todos/{todo}/rollback', 'TodosController@rollback');

Route::GET('completed', 'TodosController@completed');

Route::GET('todos/{todo}/complete', 'TodosController@complete');


Route::GET('todos/{todo}/delete', 'TodosController@destroy');

Route::POST('todos/{todo}/update-todos', 'TodosController@update');
Route::get('todos/{todo}/edit', 'TodosController@edit');

Route::post('create-todos', 'TodosController@store');
Route::get('new-todos', 'TodosController@create');

Route::get('todos/{todo}', 'TodosController@show');
Route::get('todos', 'TodosController@index');

Route::get('/', 'PageController@index');

//  Todo controller ends from here




Route::get('/', function () {
    return view('register');
});

// Route::resource('roles','AdminControllers\RolesController')->name('roles');

//User Routes
Route::match(['get', 'post'], '/add-user', 'UserController@addUser')->name('addUser');
// Route::get('/view-users', 'UserController@viewAllUsers')->name('viewAllUsers');
Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/view-users', 'UserController@viewAllUsers')->name('viewAllUsers');
});
Route::match(['get', 'post'], '/edit-user/{id}', 'UserController@editUser')->name('editUser');
Route::get('delete-user/{id}', 'UserController@deleteUser')->name('deleteUser');

//User Profile Route
Route::match(['get','post'],'/view-profile', 'UserController@viewProfile')->name('viewProfile');
Route::put('/view-profile', 'UserController@update')->name('users.update-profile');
Route::put('/password-update/{id}', 'UserController@updatePassword')->name('update_pwd');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected $fillable = [
        'name',
        'description'
        
    ];
}

app/departments.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class departments extends Model
{
    protected $fillable=[
        'name',
    ];
}

app/Http/Controllers/DepartmentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Department;

class DepartmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('departments.index')->with('departments', Department::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('departments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this -> validate(request(), [
            'name' => 'required | min:6 | max: 30',
            'description' => 'required'
        ]);

        $data = \request()->all();

        $department = new Department();
        $department -> name = $data['name'];
        $department -> description = $data['description'];
        $department -> save();

        session()->flash('success', 'Department created successfully.');

        return \redirect('/departments');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('departments.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $department = Department::find($id);
        return \view('departments.edit', compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'description'=>'required',
           
        ]);

        $department = Department::find($id);
            $department->name = $request->get('name');
            $department->description = $request->get('description');
          

        $department->save();
        return redirect('/departments')->with('update', 'Department Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $department = Department::find($id);
        $department->delete();

        return \redirect('/departments')->with('delete','Department is deleted');
    }
}

resources/views/departments/create.blade.php
@extends('vendor/main')
@section('title')
<title>Department Management System |Add new Department|</title>
@endsection

@section('content')
<!-- start page container -->
<div class="page-container">
    <!-- start page content -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Add Department </div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href=" /home ">Home</a>&nbsp;<i
                                class="fa fa-angle-right"></i>
                        </li>
                        <li class="active">Add Department</li>
                    </ol>
                </div>
            </div>


            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card card-default">
                        <div class="card-header">
                            Basic information of Department
                        </div>
                        <div class="card-body">
                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul class="list-group">
                                    @foreach ($errors->all() as $error)
                                    <li class="list-group-item">
                                        {{$error}}
                                    </li>

                                    @endforeach
                                </ul>
                            </div>

                            @endif

                            <form action=" {{route('departments.store')}} " method="POST">
                                @csrf
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" name="name" id="name"
                                        placeholder="Enter Department's name here" autofocus />
                                </div>

                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea class="form-control" name="description" id="description" cols="30"
                                        rows="10" placeholder="Enter your department's description here"></textarea>
                                </div>

                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-success ">Create Department</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end page content -->

</div>
<!-- end page container -->
@endsection

resources/views/departments/edit.blade.php
@extends('vendor/main')
@section('title')
<title>Department Management System |Update department|</title>
@endsection

@section('content')
<!-- start page container -->
<div class="page-container">
    <!-- start page content -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Update department </div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href=" /home ">Home</a>&nbsp;<i
                                class="fa fa-angle-right"></i>
                        </li>
                        <li class="active">Update department</li>
                    </ol>
                </div>
            </div>


            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card card-default">
                        <div class="card-header">
                            Basic information of department
                        </div>
                        <div class="card-body">
                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul class="list-group">
                                    @foreach ($errors->all() as $error)
                                    <li class="list-group-item">
                                        {{$error}}
                                    </li>

                                    @endforeach
                                </ul>
                            </div>

                            @endif

                            <form action="{{route('departments.update', $department->id)}}" method="POST">
                                @method('PATCH')
                                @csrf
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" name="name" id="name"
                                        placeholder="Enter deapartment's name here" autofocus value="{{$department->name}}" />
                                </div>
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <input type="text" class="form-control" name="description" id="description"  
                                        placeholder="Enter client's email here" value=" {{$department->description}} " />
                                </div>

                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-success ">Update department</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end page content -->

</div>
<!-- end page container -->
@endsection

resources/views/departments/index.blade.php
@extends('vendor/main')
@section('title')
<title>Department management system </title>
@endsection

@section('content')

<div class="page-container">

    <div class="page-content-wrapper">

        <div class="page-content">
            <div class="page-bar">

                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        {{-- <div class="page-title">User No. {{$user->id}}</div> --}}
                </div>
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href=" /home ">Home</a>&nbsp;<i
                            class="fa fa-angle-right"></i>
                    </li>
                    <li class="active">Department</li>
                </ol>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6-offset col-md-6"> {{-- session message starts --}}
                @if (session()->has('success'))
                <div class="alert alert-success">
                    {{session()->get('success')}}
                </div>
                @endif
                @if (session()->has('complete'))
                <div class="alert alert-success">
                    {{session()->get('complete')}}
                </div>
                @endif

                @if (session()->has('delete'))
                <div class="alert alert-danger">
                    {{session()->get('delete')}}
                </div>
                @endif

                @if (session()->has('update'))
                <div class="alert alert-info">
                    {{session()->get('update')}}
                </div>
                @endif
                {{-- session message ends --}}</div>


            <div class="col-md-12">
                <div class="tabbable-line">
                <ul class="nav customtab nav-tabs" href="/departments.index#tab1" ole="tablist">
                    <li class="nav-item"><a onclick="switch_div(1)" class="nav-link  active"
                            data-toggle="tab">List
                            View</a></li>
                    <li class="nav-item"><a onclick="switch_div(2)" class="nav-link " data-toggle="tab">Grid
                            View</a></li>
                </ul>

                <div class="card card-topline-purple">


                    <div class="card-head">
                        <header>All Department List</header>
                        <div class="tools">
                            <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                            <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                            <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                        </div>
                    </div>
                    <div class="card-body ">
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-6">
                                <div class="btn-group">
                                    <a href="{{ route('departments.create') }}" id="addRow" class="btn btn-info"
                                        style="margin-right: 10px;">
                                        Add New <i class="fa fa-plus"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6 col-6">
                                <div class="btn-group pull-right">
                                    <a class="btn deepPink-bgcolor  btn-outline dropdown-toggle"
                                        data-toggle="dropdown">Tools
                                        <i class="fa fa-angle-down"></i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li>
                                            <a href="javascript:;">
                                                <i class="fa fa-print"></i> Print </a>
                                        </li>
                                        <li>
                                            <a href="javascript:;">
                                                <i class="fa fa-file-pdf-o"></i> Save as
                                                PDF </a>
                                        </li>
                                        <li>
                                            <a href="javascript:;">
                                                <i class="fa fa-file-excel-o"></i>
                                                Export to Excel </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                        <div class="table-scrollable">
                            <table
                                class="table table-striped table-bordered table-hover table-checkable order-column valign-middle"
                                id="example4">
                                <thead>
                                    <tr>
                                        <th>S.N.</th>
                                        <th> Name </th>
                                        <th>Description</th>
                                        <th style="text-align:center;"> Action </th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach($departments as $key=>$department)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $department->name }}</td>

                                        <td>
                                            {{ $department->description }}

                                        </td>
                                        <td style="display:flex; padding-top: 24px;;"
                                            class="center">
                                            <a href=" {{route('departments.edit', $department->id)}} "
                                                class="btn btn-primary btn-xs">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <form
                                                action="{{route('departments.destroy',$department->id)}}"
                                                method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit"
                                                    class="btn btn-danger btn-xs">
                                                    <i class="fa fa-trash-o "></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

@section('css')
<!-- data tables -->
<link href="{{ asset('assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection

@section('scripts')
<!-- data tables -->
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/pages/table/table_data.js') }}"></script>


<script src="{{ asset('assets/js/sweetalert.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.sweet-alert.custom.js') }}"></script>



@endsection