routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//  Clients controller starts from here

use App\Http\Controllers\UserController;

Route::resource('clients', 'ClientsController');


// Departments controller starts from here
Route::resource('departments', 'DepartmentsController');

//  Clients controller starts from here


//  Todo controller starts from here

Route::GET('todos/{todo}/rollback', 'TodosController@rollback');

Route::GET('completed', 'TodosController@completed');

Route::GET('todos/{todo}/complete', 'TodosController@complete');


Route::GET('todos/{todo}/delete', 'TodosController@destroy');

Route::POST('todos/{todo}/update-todos', 'TodosController@update');
Route::get('todos/{todo}/edit', 'TodosController@edit');

Route::post('create-todos', 'TodosController@store');
Route::get('new-todos', 'TodosController@create');

Route::get('todos/{todo}', 'TodosController@show');
Route::get('todos', 'TodosController@index');

Route::get('/', 'PageController@index');

//  Todo controller ends from here




Route::get('/', function () {
    return view('register');
});

// Route::resource('roles','AdminControllers\RolesController')->name('roles');

//User Routes
Route::match(['get', 'post'], '/add-user', 'UserController@addUser')->name('addUser');
// Route::get('/view-users', 'UserController@viewAllUsers')->name('viewAllUsers');
Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/view-users', 'UserController@viewAllUsers')->name('viewAllUsers');
});
Route::match(['get', 'post'], '/edit-user/{id}', 'UserController@editUser')->name('editUser');
Route::get('delete-user/{id}', 'UserController@deleteUser')->name('deleteUser');

//User Profile Route
Route::match(['get','post'],'/view-profile', 'UserController@viewProfile')->name('viewProfile');
Route::put('/view-profile', 'UserController@update')->name('users.update-profile');
Route::put('/password-update/{id}', 'UserController@updatePassword')->name('update_pwd');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'name',
        'email',
        'phone_no',
        'city',
        'address',
        'company_name'
    ];
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use App\Client;

use Illuminate\Http\Request;

class ClientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::all();
        return \view('/clients/index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'email'=>'required',
            'phone_no'=>'required',
            'city'=>'required'
        ]);

        $client = new Client([
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'phone_no' => $request->get('phone_no'),
            'city' => $request->get('city'),
            'address' => $request->get('address'),
            'company_name' => $request->get('company_name')
        ]);
        $client->save();
        return redirect('/clients')->with('success', 'Client saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::find($id);
        return \view('clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'email'=>'required',
            'phone_no'=>'required',
            'city'=>'required'
        ]);

        $client = Client::find($id);
            $client->name = $request->get('name');
            $client->email = $request->get('email');
            $client->phone_no = $request->get('phone_no');
            $client->city = $request->get('city');
            $client->address = $request->get('address');
            $client->company_name = $request->get('company_name');

        $client->save();
        return redirect('/clients')->with('update', 'Client Updated!');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::find($id);
        $client->delete();

        return \redirect('/clients')->with('delete','Contact is deleted');
    }
}

resources/views/clients/create.blade.php
@extends('vendor/main')
@section('title')
<title>Client Management System |Add new client|</title>
@endsection

@section('content')
<!-- start page container -->
<div class="page-container">
    <!-- start page content -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Add Client </div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href=" /home ">Home</a>&nbsp;<i
                                class="fa fa-angle-right"></i>
                        </li>
                        <li class="active">Add Client</li>
                    </ol>
                </div>
            </div>


            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card card-default">
                        <div class="card-header">
                            Basic information of Client
                        </div>
                        <div class="card-body">
                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul class="list-group">
                                    @foreach ($errors->all() as $error)
                                    <li class="list-group-item">
                                        {{$error}}
                                    </li>

                                    @endforeach
                                </ul>
                            </div>

                            @endif

                            <form action="{{route('clients.store')}}" method="POST">
                                @csrf
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" name="name" id="name"
                                        placeholder="Enter client's name here" autofocus />
                                </div>
                                <div class="form-group">
                                    <label for="email">e -mail</label>
                                    <input type="email" class="form-control" name="email" id="email" cols="30" rows="10"
                                        placeholder="Enter client's email here" />
                                </div>
                                <div class="form-group">
                                    <label for="phone_no">Phone number</label>
                                    <input type="tel" class="form-control" name="phone_no" pattern="[0-9]{10}"
                                        id="phone_no" cols="30" rows="10" placeholder="Enter client's phone_no here" />
                                </div>
                                <div class="form-group">
                                    <label for="company_name">Company name</label>
                                    <input type="text" class="form-control" name="company_name" id="company_name"
                                        cols="30" rows="10" placeholder="Enter client's company_name here" />
                                </div>
                                <div class="form-group">
                                    <label for="city">Address</label>
                                    <input type="text" class="form-control" name="address" id="address" cols="30"
                                        rows="10" placeholder="Enter client's address here" />
                                </div>
                                <div class="form-group">
                                    <label for="city">City</label>
                                    <input type="text" class="form-control" name="city" id="city" cols="30" rows="10"
                                        placeholder="Enter client's city here" />
                                </div>
                                {{-- <div class="form-group">
                                    <label for="country">Country</label>
                                    <select class="form-control" name="country" id="country">
                                        <option value="" selected disabled hidden>Choose country name</option>
                                        <option value="nep">Nepal</option>
                                        <option value="ind">India</option>
                                    </select>
                                </div> --}}

                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-success ">Create Client</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end page content -->

</div>
<!-- end page container -->
@endsection

resources/views/clients/edit.blade.php
@extends('vendor/main')
@section('title')
<title>Client Management System |Update client|</title>
@endsection

@section('content')
<!-- start page container -->
<div class="page-container">
    <!-- start page content -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Update Client </div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href=" /home ">Home</a>&nbsp;<i
                                class="fa fa-angle-right"></i>
                        </li>
                        <li class="active">Update Client</li>
                    </ol>
                </div>
            </div>


            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card card-default">
                        <div class="card-header">
                            Basic information of Client
                        </div>
                        <div class="card-body">
                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul class="list-group">
                                    @foreach ($errors->all() as $error)
                                    <li class="list-group-item">
                                        {{$error}}
                                    </li>

                                    @endforeach
                                </ul>
                            </div>

                            @endif

                            <form action="{{route('clients.update', $client->id)}}" method="POST">
                                @method('PATCH')
                                @csrf
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" name="name" id="name"
                                        placeholder="Enter client's name here" autofocus value="{{$client->name}}" />
                                </div>
                                <div class="form-group">
                                    <label for="email">e -mail</label>
                                    <input type="email" class="form-control" name="email" id="email" cols="30" rows="10"
                                        placeholder="Enter client's email here" value=" {{$client->email}} " />
                                </div>
                                <div class="form-group">
                                    <label for="phone_no">Phone number</label>
                                    <input type="tel" class="form-control" name="phone_no" pattern="[0-9]{10}"
                                        id="phone_no" cols="30" rows="10" placeholder="Enter client's phone_no here"
                                        value="{{$client->phone_no}}" />
                                </div>
                                <div class="form-group">
                                    <label for="company_name">Company name</label>
                                    <input type="text" class="form-control" name="company_name" id="company_name"
                                        cols="30" rows="10" placeholder="Enter client's company_name here"
                                        value="{{$client->company_name}}" />
                                </div>
                                <div class="form-group">
                                    <label for="city">Address</label>
                                    <input type="text" class="form-control" name="address" id="address" cols="30"
                                        rows="10" placeholder="Enter client's address here"
                                        value="{{$client->address}}" />
                                </div>
                                <div class="form-group">
                                    <label for="city">City</label>
                                    <input type="text" class="form-control" name="city" id="city" cols="30" rows="10"
                                        placeholder="Enter client's city here" value="{{$client->city}}" />
                                </div>
                                {{-- <div class="form-group">
                                    <label for="country">Country</label>
                                    <select class="form-control" name="country" id="country">
                                        <option value="" selected disabled hidden>Choose country name</option>
                                        <option value="nep">Nepal</option>
                                        <option value="ind">India</option>
                                    </select>
                                </div> --}}

                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-success ">Update Client</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end page content -->

</div>
<!-- end page container -->
@endsection

resources/views/clients/index.blade.php
@extends('vendor/main')
@section('title')
<title>Client management system | homepage |</title>
@endsection

@section('content')
<!-- start page container -->
<div class="page-container">

    <!-- start page content -->
    <div class="page-content-wrapper">

        <div class="page-content">
            <div class="page-bar">


                {{-- session message starts --}}
                @if (session()->has('success'))
                <div class="alert alert-success">
                    {{session()->get('success')}}
                </div>
                @endif
                @if (session()->has('complete'))
                <div class="alert alert-success">
                    {{session()->get('complete')}}
                </div>
                @endif

                @if (session()->has('delete'))
                <div class="alert alert-danger">
                    {{session()->get('delete')}}
                </div>
                @endif

                @if (session()->has('update'))
                <div class="alert alert-info">
                    {{session()->get('update')}}
                </div>
                @endif
                {{-- session message ends --}}


                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">All Clients</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href=" /home ">Home</a>&nbsp;<i
                                class="fa fa-angle-right"></i>
                        </li>
                        <li class="active">All Clients</li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="tabbable-line">
                        <ul class="nav customtab nav-tabs" href="/clients.index#tab1" ole="tablist">
                            <li class="nav-item"><a onclick="switch_div(1)" class="nav-link  active"
                                    data-toggle="tab">List
                                    View</a></li>
                            <li class="nav-item"><a onclick="switch_div(2)" class="nav-link " data-toggle="tab">Grid
                                    View</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active  fontawesome-demo" id="show_1">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="card card-topline-red">
                                            <div class="card-head">
                                                <header></header>
                                                <div class="tools">
                                                    <a class="fa fa-repeat btn-color box-refresh"
                                                        href="javascript:;"></a>
                                                    <a class="t-collapse btn-color fa fa-chevron-down"
                                                        href="javascript:;"></a>
                                                    <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                                                </div>
                                            </div>
                                            <div class="card-body ">
                                                <div class="row">
                                                    <div class="col-md-6 col-sm-6 col-6">
                                                        <div class="btn-group">
                                                            <a href="/clients/create" id="addRow" class="btn btn-info">
                                                                Add New <i class="fa fa-plus"></i>
                                                            </a>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6 col-sm-6 col-6">
                                                        <div class="btn-group pull-right">
                                                            <a class="btn deepPink-bgcolor  btn-outline dropdown-toggle"
                                                                data-toggle="dropdown">Tools
                                                                <i class="fa fa-angle-down"></i>
                                                            </a>
                                                            <ul class="dropdown-menu pull-right">
                                                                <li>
                                                                    <a href="javascript:;">
                                                                        <i class="fa fa-print"></i> Print </a>
                                                                </li>
                                                                <li>
                                                                    <a href="javascript:;">
                                                                        <i class="fa fa-file-pdf-o"></i> Save as
                                                                        PDF </a>
                                                                </li>
                                                                <li>
                                                                    <a href="javascript:;">
                                                                        <i class="fa fa-file-excel-o"></i>
                                                                        Export to Excel </a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="table-scrollable">
                                                    <table
                                                        class="table table-striped table-bordered table-hover table-checkable order-column valign-middle"
                                                        id="example4">
                                                        <thead>
                                                            <tr>
                                                                <th></th>
                                                                <th> Name </th>
                                                                <th> Email </th>
                                                                <th> Phone number </th>
                                                                <th> Company name </th>
                                                                <th> Address </th>
                                                                <th>City</th>
                                                                <th> Action </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            @foreach($clients as $client)
                                                            <tr class="odd gradeX">
                                                                <td class="patient-img">
                                                                    <img src="../assets/img/std/std1.jpg" alt="">
                                                                </td>
                                                                <td class="center">{{$client->name}}</td>
                                                                <td><a
                                                                        href="mailto:{{$client->email}}">{{$client->email}}</a>
                                                                </td>
                                                                <td> <a
                                                                        href="tel:{{$client->phone_no}}">{{$client->phone_no}}</a>
                                                                </td>
                                                                <td class="center">{{$client->company_name}}</td>
                                                                <td class="center">{{$client->address}}</td>
                                                                <td class="center">{{$client->city}}</td>
                                                                <td style="display:flex; padding-top: 24px;;"
                                                                    class="center">
                                                                    <a href=" {{route('clients.edit', $client->id)}} "
                                                                        class="btn btn-primary btn-xs">
                                                                        <i class="fa fa-pencil"></i>
                                                                    </a>
                                                                    <form
                                                                        action="{{route('clients.destroy',$client->id)}}"
                                                                        method="POST">
                                                                        @csrf
                                                                        @method('DELETE')
                                                                        <button type="submit"
                                                                            class="btn btn-danger btn-xs">
                                                                            <i class="fa fa-trash-o "></i>
                                                                        </button>
                                                                    </form>
                                                                </td>
                                                            </tr>
                                                            @endforeach
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane  " id="show_2">
                                @foreach($clients as $client)

                                <div class="">
                                    <div class="col-md-4">
                                        <div class="card card-topline-aqua">
                                            <div class="card-body no-padding ">
                                                <div class="doctor-profile">
                                                    <img src="../assets/img/std/std1.jpg" class="doctor-pic" alt="">
                                                    <div class="profile-usertitle">
                                                        <div class="doctor-name">{{$client->name}} </div>
                                                        <div class="name-center"> <a
                                                                href="mailto:{{$client->email}}">{{$client->email}}</a>
                                                        </div>
                                                    </div>
                                                    <p>{{$client->address}}<br />{{$client->city}}</p>
                                                    <div>
                                                        <p><i class="fa fa-phone"></i><a
                                                                href="tel:{{$client->phone_no}}">
                                                                {{$client->phone_no}}</a></p>
                                                    </div>
                                                    <div class="profile-userbuttons">
                                                        <a href="staff_profile.html"
                                                            class="btn btn-circle deepPink-bgcolor btn-sm">Read
                                                            More</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                @endforeach


                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
    <!-- end page content -->

</div>
<!-- end page container -->
@endsection